### ISSUE TITLE
Results folder creates only '0' folder during training

### ISSUE THREAD

**Issue by JSchreijer** [MAGICS-LAB/DNABERT_S#13]
Hi!

DNABERT_S is a great model and I've been having fun working with it! I have been rerunning some of the code and found that, during the training of the debug_train.csv, the results are saved as one folder with the name '0'. However, the previous time I did this it resulted in three folders named '0', '100' and 'best'. I am not sure what triggered this change as I have not changed anything regarding my settings (I have only slightly lowered train_batch_size and max_length for my device, but this was already in place during the first time I ran the training). Additionally during the training, no errors occur that could give me a hint! What could be the source of this (it seems) unfinished training?

**Comment by Zhihan1996** [comment]
Here, the `0` and `100` basically indicate the number of training steps. The checkpoints saved under each folder is the model checkpoint at that step. 

The default saving frequency is 100 steps. So, this is not an error at all. Since you reduce the batch size, you get more training steps with the same amount of data, so you get one more checkpoint.
