### ISSUE TITLE
Questions about the training setting

### ISSUE THREAD

**Issue by HelloWorldLTY** [MAGICS-LAB/DNABERT_S#22]
Hi, thanks for your great work. I wonder in the training process, why the sampling is necessary and what is the consideration of sampling sequence number, thanks a lot.

```
Each training sample of DNABERT-S is a pair of non-overlapping DNA sequences extracted from the same genome.
The dataset is constructed with the reference genomes from GenBank [Benson et al., 2012]. We obtained 47923 pairs
from 17636 viral genomes, 1 million pairs from 5011 fungi genomes, and 1 million pairs from 6402 bacteria genomes.
We randomly selected 2 million pairs from the entire 2047923 pairs of DNA sequences to construct the training data.
The rest pairs are treated as validation data. All the DNA sequences are 10000 bp in length.
```

**Comment by Zhihan1996** [comment]
Thank you for interests in our work! 

Since the genome size of different species (like human and virus) differs hugely, if we instead using the whole genome of each species, it will results in a largely unbalanced datasets. So our main consideration behind the data construction and sampling is to make the data diverse (covers as much species as possible) and balanced.
